from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import CountryViewSet

"""
Django REST framework automatically appends a forward slash (/) to the end of any endpoints generated by 
DefaultRouter. You can disable this behavior like so:
This will disable the forward slash at the end of endpoints.
"""
# router = DefaultRouter(trailing_slash=False)

router = DefaultRouter()
router.register(r"countries", CountryViewSet)

urlpatterns = [
    path("", include(router.urls))
]
